remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
- charts/incubator
- charts/stable
excluded-charts:
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
- k8s-at-home-libraries=https://philstevenson.github.io/library-charts
- k8s-at-home=https://philstevenson.github.io/charts
- jetstack=https://charts.jetstack.io
